#pragma once

#include "Engine/Core.hpp"
#include "Engine/Debug.hpp"
#include "Engine/Logger.hpp"
#include "Engine/Engine.hpp"
#include "Engine/DeltaTime.hpp"
#include "Engine/GameLayer.hpp"
#include "Engine/EntryPoint.hpp"
#include "Engine/GameSettings.hpp"
#include "Engine/GameLayerStack.hpp"
#include "Engine/ResourceHolder.hpp"

#include "Events/Event.hpp"
#include "Events/MouseEvents.hpp"
#include "Events/WindowEvents.hpp"
#include "Events/KeyboardEvents.hpp"

#include "Graphics/Rect.hpp"
#include "Graphics/Color.hpp"
#include "Graphics/Sprite.hpp"
#include "Graphics/Vertex.hpp"
#include "Graphics/Shader.hpp"
#include "Graphics/Camera.hpp"
#include "Graphics/Window.hpp"
#include "Graphics/Texture.hpp"
#include "Graphics/Drawable.hpp"
#include "Graphics/Renderer.hpp"
#include "Graphics/VertexArray.hpp"
#include "Graphics/IndexBuffer.hpp"
#include "Graphics/VertexBuffer.hpp"
#include "Graphics/BufferLayout.hpp"
#include "Graphics/Transformable.hpp"

#include "Graphics/Shapes/Circle.hpp"
#include "Graphics/Shapes/Rectangle.hpp"

#include "Input/Mouse.hpp"
#include "Input/Keyboard.hpp"

#include "Utility.hpp"
